<a href="https://colab.research.google.com/github/godsen1/ColabAI/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпорт модуля pandas

In [1]:
import pandas as pd

Дані про пасажирів корабля:
* pclass -- клас білета(перший, другий або третій)
* sex -- стать
* age -- вік
* sibsp -- кількість братів\сестер та чоловіків\дружин на борту
* parch -- кількість дітей та батьків на борту
* fare -- вартість поїздки
* embarked -- Порт посадки (C = Шербур, Q = Квінстаун, S = Саутгемптон)

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module2/data/ship_passengers.csv",
                 index_col="Unnamed: 0")

# Завдання 1

Вивести загальну інформацію про таблицю: кількість рядків та стовпців, назви стовпців та їхній тип даних, в яких стовпцях є пропущені значення

# Завдання 2
Скільки пасажирів сіло у Квінстауні?

# Завдання 3
Виведіть стать, вік та вартість поїздки для пасажирів з білетом першого класу

# Завдання 4
Ввиведіть дані про неповнолітніх чоловіків з Шербура

# Завдання 5
Створіть новий стовпчик relatives -- загальна кількість родичів на борту для кожного пасажира

In [3]:
df.columns

Index(['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked'], dtype='object')

In [4]:
df[["sibsp", "parch"]]

     sibsp  parch
0        1      0
1        1      0
2        0      0
3        1      0
4        0      0
..     ...    ...
886      0      0
887      0      0
888      1      2
889      0      0
890      0      0

[891 rows x 2 columns]

In [7]:
df["sipar"]= df["sibsp"] + df["parch"]

In [8]:
df

     pclass     sex   age  sibsp  parch     fare embarked  sipar
0         3    male  22.0      1      0   7.2500        S      1
1         1  female  38.0      1      0  71.2833        C      1
2         3  female  26.0      0      0   7.9250        S      0
3         1  female  35.0      1      0  53.1000        S      1
4         3    male  35.0      0      0   8.0500        S      0
..      ...     ...   ...    ...    ...      ...      ...    ...
886       2    male  27.0      0      0  13.0000        S      0
887       1  female  19.0      0      0  30.0000        S      0
888       3  female   NaN      1      2  23.4500        S      3
889       1    male  26.0      0      0  30.0000        C      0
890       3    male  32.0      0      0   7.7500        Q      0

[891 rows x 8 columns]

# Завдання 6
Видаліть стовпчик, в якому найбільше пропусків. Якщо пропущені значення ще залишаться, видаліть рядки з пропусками

In [12]:
col1= df.isnull().sum().idxmax()

In [16]:
df.drop(columns=col1, inplace=True)

In [17]:
df

     pclass     sex  sibsp  parch     fare embarked  sipar
0         3    male      1      0   7.2500        S      1
1         1  female      1      0  71.2833        C      1
2         3  female      0      0   7.9250        S      0
3         1  female      1      0  53.1000        S      1
4         3    male      0      0   8.0500        S      0
..      ...     ...    ...    ...      ...      ...    ...
886       2    male      0      0  13.0000        S      0
887       1  female      0      0  30.0000        S      0
888       3  female      1      2  23.4500        S      3
889       1    male      0      0  30.0000        C      0
890       3    male      0      0   7.7500        Q      0

[891 rows x 7 columns]

In [18]:
df.isnull().sum()

pclass      0
sex         0
sibsp       0
parch       0
fare        0
embarked    2
sipar       0
dtype: int64

In [21]:
df.dropna(inplace=True)

In [22]:
df

     pclass     sex  sibsp  parch     fare embarked  sipar
0         3    male      1      0   7.2500        S      1
1         1  female      1      0  71.2833        C      1
2         3  female      0      0   7.9250        S      0
3         1  female      1      0  53.1000        S      1
4         3    male      0      0   8.0500        S      0
..      ...     ...    ...    ...      ...      ...    ...
886       2    male      0      0  13.0000        S      0
887       1  female      0      0  30.0000        S      0
888       3  female      1      2  23.4500        S      3
889       1    male      0      0  30.0000        C      0
890       3    male      0      0   7.7500        Q      0

[889 rows x 7 columns]